# 1. Identidade e Porta
spring.application.name=sales
server.port=4000

# 2. Conexao com o Banco de Dados (Onde o Docker esta)
spring.datasource.url=jdbc:postgresql://localhost:9876/tickets-sales
spring.datasource.username=pg-tickets-sales
spring.datasource.password=tickets-sales-password
spring.datasource.driver-class-name=org.postgresql.Driver

# 3. Comportamento do JPA (Criacao de tabelas)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true