###
@urlServer = http://localhost:8081

###
GET {{urlServer}}/users/status
###

GET {{urlServer}}/ccn

###
POST {{urlServer}}/ccn
Content-Type: application/json

{
  "name": "Master"
}

###
GET {{urlServer}}/users

###
POST {{urlServer}}/users
Content-Type: application/json

{
  "name": "Maria Fernanda",
  "creditCardNetworkId": "e97fa53b-0662-4cc4-8db4-0c5d9d6a7107",
  "email": "mariafernanda@web.ufop.edu.br",
  "password": "123456"
}

###
GET {{urlServer}}/users/63f9ac31-b67f-4366-8128-7f82e72f6060

###
GET {{urlServer}}/users/name/Maria

###
PUT {{urlServer}}/users
Content-Type: application/json

{
  "id": "71b977da-10cf-4ba0-b9af-234df7731075",
  "name": "Maria Tereza",
  "city": "Itabira"
}
###
DELETE {{urlServer}}/users
Content-Type: application/json

{
  "id": "71b977da-10cf-4ba0-b9af-234df7731075",
  "password": "123456"
}















