### --- TESTES DE EVENTOS ---

### Configuração da URL (Porta 4000)
@urlSales = http://localhost:4000

### 1. Verificar Status
GET {{urlSales}}/events/status

### 2. Criar um Evento
POST {{urlSales}}/events
Content-Type: application/json

{
  "description": "Show do Rock in Rio 2025",
  "type": 1,
  "price": 450.00,
  "date": "2025-09-20T20:00:00",
  "startSales": "2025-01-01T08:00:00",
  "endSales": "2025-09-19T23:59:00"
}

### 3. Listar todos
GET {{urlSales}}/events

### 4. Buscar por ID
GET {{urlSales}}/events/9bc4b360-e96f-4e4c-b6d0-fde454161958

### --- TESTES DE VENDAS ---


### 1. Criar uma Venda
# Para funcionar, você precisa pegar um ID de Evento VÁLIDO que você criou lá em cima
# e um ID de usuário qualquer (invente um UUID se não tiver o microsserviço Users rodando)
POST {{urlSales}}/sales
Content-Type: application/json

{
  "eventId": "9bc4b360-e96f-4e4c-b6d0-fde454161958",
  "userId": "74ff0eb8-ce65-4674-9efb-54857b651cca"
}

### 2. Listar todas as Vendas
GET {{urlSales}}/sales

### 3. Consultar Venda Específica (Copie o ID gerado no passo 1)
GET {{urlSales}}/sales/dc1fd2f0-2f60-457d-b905-e375bca0b0a4