###
@urlServer = http://localhost:4000

### --- EVENTOS ---

###
GET {{urlServer}}/events/status

###
GET {{urlServer}}/events

###
POST {{urlServer}}/events
Content-Type: application/json

{
  "description": "Show do Rock - UFOP",
  "type": 1,
  "price": 100.00,
  "date": "2025-12-25T20:00:00",
  "startSales": "2025-01-01T08:00:00",
  "endSales": "2025-12-24T23:59:00"
}

###
GET {{urlServer}}/events/d8e6297d-eeee-4cba-a224-ee6354c745bc

###
PUT {{urlServer}}/events/d8e6297d-eeee-4cba-a224-ee6354c745bc
Content-Type: application/json

{
  "description": "Show do Rock - ADIADO",
  "type": 1,
  "price": 100.00,
  "date": "2026-01-01T20:00:00",
  "startSales": "2025-01-01T08:00:00",
  "endSales": "2025-12-31T23:59:00"
}

###
DELETE {{urlServer}}/events/d8e6297d-eeee-4cba-a224-ee6354c745bc


### --- VENDAS ---

###
GET {{urlServer}}/sales/status

###
GET {{urlServer}}/sales

###
POST {{urlServer}}/sales
Content-Type: application/json

{
  "eventId": "59807b4b-82d6-4555-8604-4a9f8935f771",
  "userId": "63f9ac31-b67f-4366-8128-7f82e72f6060"
}

###
GET {{urlServer}}/sales/d2b4e65a-0205-4d48-9774-136294ef0e0cI

###
GET {{urlServer}}/sales/user/63f9ac31-b67f-4366-8128-7f82e72f6060

###
PUT {{urlServer}}/sales
Content-Type: application/json

{
  "id": "COLE-O-UUID-DA-VENDA-AQUI",
  "saleStatus": 2
}

###
DELETE {{urlSales}}/sales
Content-Type: application/json

{
  "id": "COLE-O-UUID-DA-VENDA-AQUI",
  "reason": "Cliente desistiu da compra pois achou caro"
}